// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrhfvjnfhhaabuhozknu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyaGZ2am5maGhhYWJ1aG96a251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjEyNjEsImV4cCI6MjA2NDczNzI2MX0.PuQkHnwTVTG8BfMjRMCTA0KGbHPdlNS84joUwVkJ-BY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);